model:
  name: 'resnet18'
  params:
    pre: false
    planes: [16, 16, 32, 64]


data_dir: 'data'
save_dir: 'save/resnet18'

epochs: 100
batch_size: 32
lr: 0.1
momentum: 0.9
weight_decay: 5.0e-4
gpu: true

scheduler:
  type: 'step'
  step_size: 30
  gamma: 0.1

augmentation:
  mixup: false
  mixup_alpha: 0.8
  cutout: false
  cutout_length: 16